version: "3.9"

services:
  frontend: # Unico servizio, focalizzato sullo sviluppo
    build:
      context: .
      dockerfile: Dockerfile # Modificato da Dockerfile.dev a Dockerfile
    container_name: frontend_angular_dev
    working_dir: /app
    # Il comando è stato spostato nel CMD del Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - .:/app # Mappa i sorgenti per il live-reloading
      - /app/node_modules # Isola node_modules nel container per evitare conflitti con l'host
      - npm_cache_frontend:/root/.npm # Cache per npm per velocizzare installazioni future
    networks:
      - order_app_network # Nome della rete condivisa con il backend
    restart: unless-stopped
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true" # Utile per il live-reloading in alcuni ambienti Docker

networks:
  order_app_network:
    external: true
    name: app-network # Nome REALE della rete Docker a cui connettersi (definita dal backend o esternamente)

volumes:
  npm_cache_frontend: # Volume per la cache di npm
