version: "3.9"

services:
  # Servizio Frontend per lo SVILUPPO
  dev:
    image: node:20-alpine
    container_name: frontend_angular_dev_env
    working_dir: /app
    command: sh -c "npm install -g @angular/cli@latest && echo 'Ambiente di sviluppo frontend pronto.' && tail -f /dev/null"
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - /app/node_modules # Isola node_modules nel container per prestazioni
      - npm_cache_frontend_dev:/root/.npm
    networks:
      - backend_network # Nome logico usato qui, mappato sotto

  # Servizio Frontend per la PRODUZIONE
  prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend_angular_prod_app
    ports:
      - "8080:80" # Esempio, la porta host può essere diversa
    networks:
      - backend_network # Nome logico usato qui, mappato sotto
    restart: unless-stopped

networks:
  backend_network: # Nome logico usato nei servizi sopra
    external: true
    name: app-network # Nome REALE della rete Docker definita dal backend

volumes:
  npm_cache_frontend_dev:
