import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { AuthService } from '../../services/auth.service';
import { QRCodeComponent } from 'angularx-qrcode';

@Component({
  selector: 'app-profile',
  standalone: true,
  imports: [CommonModule, FormsModule, QRCodeComponent],
  template: `
    <div class="container mt-5">
      <h2>Profile</h2>
      <button (click)="logout()" class="btn btn-danger mb-4">Logout</button>

      <div class="card">
        <div class="card-header">Two-Factor Authentication</div>
        <div class="card-body">
          
          <!-- Setup 2FA Button -->
          <div *ngIf="!setupMode && !qrCodeData">
            <button (click)="setup2fa()" class="btn btn-primary">Enable 2FA</button>
            <p class="text-muted mt-2">Secure your account with Google Authenticator.</p>
          </div>

          <!-- QR Code Display & Verification -->
          <div *ngIf="setupMode">
            <h5>Setup 2FA</h5>
            <p>1. Scan this QR code with your authenticator app.</p>
            <div class="my-3">
               <qrcode [qrdata]="qrCodeData" [width]="256" [errorCorrectionLevel]="'M'"></qrcode>
            </div>
            <p>2. Enter the code generated by the app.</p>
            
            <div class="mb-3">
                <input type="text" class="form-control" [(ngModel)]="verifyCode" placeholder="123456" style="max-width: 200px;">
            </div>
            <button (click)="enable2fa()" class="btn btn-success">Verify & Enable</button>
            <button (click)="cancelSetup()" class="btn btn-secondary ms-2">Cancel</button>
          </div>

          <!-- Disable 2FA -->
          <div *ngIf="false"> <!-- Logic to check if enabled is tricky without extra API call, assumed handled by user flow or error handling -->
             <button class="btn btn-warning">Disable 2FA</button>
          </div>
          
          <div *ngIf="message" class="alert alert-info mt-3">{{ message }}</div>
        </div>
      </div>
    </div>
  `
})
export class ProfileComponent implements OnInit {
  setupMode = false;
  qrCodeData = '';
  secret = '';
  verifyCode = '';
  message = '';

  constructor(private authService: AuthService) {}

  ngOnInit() {}

  logout() {
    this.authService.logout();
  }

  setup2fa() {
    this.authService.setup2fa().subscribe({
      next: (res) => {
        this.secret = res.secret;
        this.qrCodeData = res.qrCode;
        this.setupMode = true;
        this.message = '';
      },
      error: (err) => this.message = 'Error starting setup.'
    });
  }

  enable2fa() {
    this.authService.enable2fa(this.secret, this.verifyCode).subscribe({
      next: (res) => {
        this.message = '2FA Enabled Successfully!';
        this.setupMode = false;
        this.qrCodeData = '';
        this.secret = '';
        this.verifyCode = '';
      },
      error: (err) => this.message = err.error.message || 'Verification failed.'
    });
  }

  cancelSetup() {
    this.setupMode = false;
    this.qrCodeData = '';
    this.secret = '';
    this.message = '';
  }
}
